### ISSUE TITLE
GetDemSlice error: segmentation fault

### ISSUE THREAD

**Issue by dalap125** [apburt/treeseg#28] opened 2020-11-25 16:17 UTC
Hi,

I'm trying to follow the example on the ReadMe with my single TLS data, but I ran into an issue with the getdemslice function. I've managed to downsample the input cloud data with the downsample function, but when I try to apply the getdemslice  function to the output of the downsample function, I get the following error: Segmentation fault.

Also, when I try to run the getdemslice function on the original point cloud (in .pcd), I get the error "[pcl::PCDWriter::writeBinary] Input point cloud has no data!" even though the file is valid (I'm able to visualize it in CloudCompare and R). 

I know it's a bit vague, but have you ran into this sort of issue before? I thought that it might be an incompatibility with the PCL library, so I downgraded to libpcl 1.9 but it didn't solve the issue. I also tried modifying the treeseg_pointtype.h file, but it didn't work.

Any ideas?
Thank you very much!

**Comment by tpet93** [comment] 2020-11-25 20:32
That error indicates the output pointcloud contains no points, as it is reported by the PCDWriter function. Not the most intuitive message.

Perhaps double check your input parameters are suitable for the size  shape of the plot you are running.


If your still having trouble you may need to inspect the getdemslice function closer to see what's happening.
As it seems to be returning an empty pointcloud.
You can do this either using lots of std::cout s or using gdb run.

gdb --args getdemslice 2 2.5 3.........
break treeseg.cpp:724
r
(Wait till the breakpoint)
Info locals

**Comment by apburt** [comment] 2021-02-01 18:41
Assuming this is now fixed - feel free to reopen if not sorted!

**Closed by apburt** 2021-02-01 18:41 UTC

**Comment by russelldj** [comment] 2022-06-03 00:51
This appears to be caused by an indexing error [here](https://github.com/apburt/treeseg/blob/076ea0949a17102fcc6ce8d33cf1d915895bf180/src/treeseg.cpp#L837) which occurs when there are no points in a given grid cell. I set these DEM values to a default (0), which let me get through this step. Perhaps there's something more inteligent.

**Comment by deeepwin** [comment] 2024-12-07 19:26
@russelldj I have the same issue. Some tiles might not have points. How did you set the DEM values to default 0?

**Comment by russelldj** [comment] 2024-12-09 13:53
I don't remember off the top of my head, sorry.

**Comment by deeepwin** [comment] 2024-12-10 20:01
No, problem. In my case it was about the data. If some tiles have not sufficient points, it causes an exception somewhere in the code. Preparing point cloud carefully and cutting it into rectangular shape solved it for me.
